In [ ]:
# !pip install tensorflow
# !pip install keras
# !pip install sklearn
# !pip install theano

In [2]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import cv2
import random
from tensorflow import keras
import numpy as np
# from tensorflow.keras import layers, Dense, Input, InputLayer, Flatten
# from tensorflow.keras.models import Sequential, Model


from keras.models import Sequential
from keras import layers
from keras.layers import Dense,Input, InputLayer, Flatten


from  matplotlib import pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline



from keras.layers.core import Dense, Activation, Dropout, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
# from keras.optimizers import  adam
from tensorflow.keras.optimizers import SGD,RMSprop, Adam

from keras.utils import np_utils
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import os
import cv2
import random 
from numpy import *
from PIL import Image
import theano

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [13]:
path_test = "./Datasets/Test/"

In [28]:
CATEGORIES = ['bright_dune', 'crater','dark_dune','impact','streak']

In [15]:
training = []

def createTrainingData():
  for category in CATEGORIES:
    path = os.path.join(path_test, category)
    class_num = CATEGORIES.index(category)
    for img in os.listdir(path):
      img_array = cv2.imread(os.path.join(path,img))
      new_array = cv2.resize(img_array, (227, 227))
      training.append([new_array, class_num])
      
createTrainingData()

In [16]:
random.shuffle(training)
X = []
y = []

for features, label in training:
  X.append(features)
  y.append(label)
X = np.array(X).reshape(-1, 227, 227, 3)
y = np.array(y)

In [17]:
X.shape

(970, 227, 227, 3)

In [18]:
X = X.astype('float32')
X /= 255

y

array([2, 1, 2, 4, 1, 0, 1, 1, 0, 1, 1, 2, 2, 1, 2, 0, 1, 1, 0, 1, 1, 2,
       2, 1, 2, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 4, 1, 2,
       1, 1, 0, 1, 0, 1, 0, 2, 1, 2, 2, 4, 2, 1, 1, 2, 1, 1, 2, 1, 0, 1,
       2, 1, 0, 1, 1, 2, 0, 2, 1, 1, 2, 0, 0, 1, 2, 1, 1, 1, 2, 4, 4, 2,
       1, 1, 0, 2, 2, 1, 2, 2, 0, 1, 1, 0, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 2, 2, 0, 2, 1, 2, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 4, 2,
       2, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1,
       1, 4, 2, 2, 2, 1, 1, 1, 2, 4, 4, 2, 1, 2, 4, 2, 2, 1, 1, 2, 0, 2,
       2, 2, 1, 4, 4, 2, 2, 1, 2, 4, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       2, 2, 1, 1, 1, 2, 4, 2, 1, 2, 2, 0, 4, 0, 1, 2, 4, 2, 2, 0, 2, 1,
       1, 2, 1, 0, 1, 4, 2, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2, 0,
       0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 0, 0,
       2, 0, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2,
       0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2,

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4)

In [20]:
batch_size = 20
nb_classes = 5
nb_epochs = 10
img_rows, img_columns = 227, 227
img_channel = 3
nb_filters = 32
nb_pool = 2
nb_conv = 3

In [21]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=96, kernel_size=(11,11), strides=(4,4), padding='same', activation=tf.nn.relu,
                           input_shape=(227, 227, 3)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D((3, 3), strides=2),
    tf.keras.layers.Conv2D(filters=256, kernel_size=(5,5), strides=(1,1), padding='same', activation=tf.nn.relu),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D((3, 3), strides=2),
    tf.keras.layers.Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='same', activation=tf.nn.relu),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='same', activation=tf.nn.relu),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='same', activation=tf.nn.relu),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling2D((2, 2), strides=2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(5,  activation=tf.nn.softmax)
])


In [22]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [23]:
model.fit(X_train, y_train, batch_size = batch_size, epochs = nb_epochs, verbose = 1, validation_data = (X_test, y_test))

Train on 776 samples, validate on 194 samples
Epoch 1/10
776/776 [==============================] - 8s 10ms/sample - loss: 2.2483 - accuracy: 0.4356 - val_loss: 1.0757 - val_accuracy: 0.5670
Epoch 2/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.8845 - accuracy: 0.6340 - val_loss: 0.8169 - val_accuracy: 0.7062
Epoch 3/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.5798 - accuracy: 0.8093 - val_loss: 0.7600 - val_accuracy: 0.7887
Epoch 4/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.4632 - accuracy: 0.8454 - val_loss: 0.9832 - val_accuracy: 0.7474
Epoch 5/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.3190 - accuracy: 0.9021 - val_loss: 0.6666 - val_accuracy: 0.8351
Epoch 6/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.2365 - accuracy: 0.9317 - val_loss: 0.7294 - val_accuracy: 0.7784
Epoch 7/10
776/776 [==============================] - 3s 4ms/sample - loss: 0.2674 - accu

In [29]:
def findClass(image_path):
    image_1 = cv2.imread(image_path)
    image_1 = cv2.resize(image_1, (227, 227))
    np.array(image_1).reshape(-1, 227, 227, 3)
    image_1 = image_1.astype('float32')
    image_1 /= 255 
    prediction = model.predict(np.array([image_1], np.float32))
    print(prediction)
    return CATEGORIES[np.argmax(prediction)]

In [43]:
testData = [
    r'./Datasets/Test/bright_dune/ESP_016576_2570_RED-0061.jpg', 
    r'./Datasets/Test/dark_dune/ESP_018334_2600_RED-0501.jpg',
    r'./Datasets/Test/streak/ESP_011289_1950_RED-0067.jpg', 
    r'./Datasets/hirise-map-proj-v3_2/slope_streak/ESP_011289_1950_RED-0230.jpg',
    r'./Datasets/hirise-map-proj-v3_2/crater/ESP_011425_1775_RED-0030-r90.jpg'
    ]

# findClass(r'./Datasets/Test/bright_dune/ESP_016576_2570_RED-0061.jpg')

for i in testData:
    print(findClass(i))

# CATEGORIES = ['bright_dune', 'crater','dark_dune','impact','streak']

[[6.5923464e-01 2.9791936e-03 3.3561331e-01 6.4134353e-10 2.1727653e-03]]
bright_dune
[[9.7521893e-09 3.7194814e-06 9.9999630e-01 5.8915806e-32 7.9319514e-17]]
dark_dune
[[8.9790113e-03 8.4225416e-02 6.5765381e-03 5.0407500e-05 9.0016860e-01]]
streak
[[5.7371776e-03 2.2821629e-01 6.4701084e-03 7.2001538e-05 7.5950444e-01]]
streak
[[1.1776655e-02 9.4800073e-01 4.0222552e-02 3.4607275e-17 3.9581378e-09]]
crater


In [20]:
import pickle

In [ ]:
# creates a HDF5 file 'my_model.h5'
model.save('models/cnn.h5')
pickle.dump( model, open( "classification_model_v1.pickle", "wb" ))