In [1]:
from tensorflow import keras
import cv2
import numpy as np
import os

In [2]:
model = keras.models.load_model(r'./models/cnn2.h5')

In [3]:
CATEGORIES = ['bright_dune', 'crater','dark_dune','impact_ejecta','slope_streak']
# CATEGORIES = ['bright_dune', 'crater','dark_dune','slope_streak', 'other']

In [9]:
def findClass(image_path):
    image_1 = cv2.imread(image_path)
    image_1 = cv2.resize(image_1, (227, 227))
    np.array(image_1).reshape(-1, 227, 227, 3)
    image_1 = image_1.astype('float32')
    image_1 /= 255 
    prediction = model.predict(np.array([image_1], np.float32))
    print(prediction)
    # print(prediction)
    return CATEGORIES[np.argmax(prediction)]

In [10]:
testData = [
    r'./Datasets/test-data/bright_dune/ESP_016576_2570_RED-0061.jpg', 
    r'./Datasets/test-data/dark_dune/ESP_018334_2600_RED-0501.jpg',
    r'./Datasets/test-data/slope_streak/ESP_011289_1950_RED-0067.jpg', 
    r'./Datasets/hirise-map-proj-v3_2/slope_streak/ESP_011289_1950_RED-0230.jpg',
    r'./Datasets/hirise-map-proj-v3_2/crater/ESP_011425_1775_RED-0030-r90.jpg',
]

# findClass(r'./Datasets/test-data/bright_dune/ESP_016576_2570_RED-0061.jpg')

for i in testData:
    print(findClass(i))
    

[[6.5926933e-01 1.4344084e-01 2.6650603e-05 2.2937864e-04 1.9703378e-01]]
bright_dune
[[3.9293582e-07 2.9123452e-01 7.0737976e-01 7.1955677e-05 1.3133792e-03]]
dark_dune
[[1.4629505e-04 1.1112979e-02 1.7007221e-02 1.7971309e-03 9.6993637e-01]]
slope_streak
[[3.6291374e-04 1.7182851e-02 1.6795844e-03 1.0825002e-05 9.8076379e-01]]
slope_streak
[[4.3498568e-07 2.7854249e-01 6.9778657e-01 7.0559377e-05 2.3599993e-02]]
dark_dune
[[9.9999654e-01 3.9063698e-07 5.2071811e-14 2.3741409e-06 6.8934798e-07]]
bright_dune


In [ ]:
for cat in CATEGORIES:
    correct = 0
    wrong = 0
    for img in os.listdir(f'./Datasets/test-data/{cat}'):
        path = os.path.join(f'./Datasets/test-data/{cat}', img)
        output = findClass(path)
        if output == cat:
            correct += 1
        else:
            wrong += 1
    print(f"Accuracy for {cat} class : {correct / (correct + wrong)}")

In [7]:
findClass("./Datasets/test2.jpg")

'crater'